version: '3.3'
services:
  redis:
    container_name: ${APP_NAME}_redis
    ports:
      - ${PORT}:6379
    volumes:
      - ./redis-data:/data
    command: --save 60 1 --loglevel warning
    image: 'redis:latest'
    restart: unless-stopped
    networks:
      - microservice

networks:
    microservice:
        name: microservice-network
        external: true